services:
  db:
    image: mysql:5.7
    # command: '--default-authentication-plugin=mysql_native_password'
    # restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=realworld
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306

volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
